repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
-   repo: https://github.com/Enter-tainer/typstyle
    rev: 'v0.11.30'  # The the revision or tag you want to use
    hooks:
      - id: typstyle
